# base config (defines defaults for experiment config)
mode: generation
output_dir: outputs/supervised/debug
model_name: t5-small
data_config:
  data_dir: data/SBIC.v2-min
  batch_size: 4
  subsample_common_stereotypes: False
  dev_size: 1000
train_config:
  optimizer: adamw
  train_steps: 200
  grad_accumulation_steps: 4
  lr: 1e-4
  eval_every: 100
eval_config:
  monitor: offensive-F1
  maximize: True
generate_config:
  do_sample: False