output_dir: outputs/debug
model_name: t5-large
data_config:
  data_dir: data/SBIC.v2
  batch_size: 4
  subsample_common_stereotypes: True
train_config:
  train_steps: 20
  grad_accumulation_steps: 4
  lr: 1e-4
  eval_every: 5
generate_config:
  do_sample: True
  temperature: 0.4