output_dir: outputs/entailment/bert
model_name: bert-base-uncased
data_config:
  data_dir: data/SBIC.v2
  batch_size: 16
train_config:
  optimizer: adamw
  train_steps: 1000
  grad_accumulation_steps: 1
  lr: 1e-5
  eval_every: 200