output_dir: outputs/t5-large/8k-small-lr
model_name: t5-large
data_config:
  subsample_common_stereotypes: True
  data_dir: data/SBIC.v2
  batch_size: 16
train_config:
  train_steps: 8000
  grad_accumulation_steps: 1
  lr: 2e-5
  eval_every: 800
generate_config:
  do_sample: True
  temperature: 0.3