output_dir: outputs/supervised/t5-3b-bs=1-lower-lr
model_name: t5-3b
data_config:
  subsample_common_stereotypes: True
  data_dir: data/SBIC+implHate
  batch_size: 2
  additional_test:
    - test-implHate
train_config:
  optimizer: adafactor
  train_steps: 8000
  grad_accumulation_steps: 64
  lr: 2e-4
  eval_every: 320
