output_dir: outputs/supervised/t5-v1_1/large
model_name: google/t5-v1_1-large
data_config:
  subsample_common_stereotypes: True
  data_dir: data/SBIC+implHate
  batch_size: 8
  additional_test:
    - test-implHate
train_config:
  train_steps: 4000
  grad_accumulation_steps: 2
  lr: 1e-4
  eval_every: 400
