output_dir: outputs/supervised/implHate/t5-small-lr
model_name: t5-large
data_config:
  subsample_common_stereotypes: True
  data_dir: data/implHate
  batch_size: 8

train_config:
  train_steps: 4000
  grad_accumulation_steps: 2
  lr: 2e-5
  eval_every: 400
