output_dir: outputs/t5-large/8k-large-lr
model_name: t5-large
data_config:
  subsample_common_stereotypes: True
  data_dir: data/SBIC.v2
  batch_size: 8
train_config:
  train_steps: 4000
  grad_accumulation_steps: 2
  lr: 5e-4
  eval_every: 400
