output_dir: outputs/supervised/t5-large/8k-small-lr
model_name: t5-large
data_config:
  subsample_common_stereotypes: True
  data_dir: data/SBIC+implHate
  batch_size: 8
  additional_test:
    - test-implHate
train_config:
  train_steps: 4000
  grad_accumulation_steps: 2
  lr: 2e-5
  eval_every: 400
