class: gpt-3
output_dir: outputs/in-context/SBIC/davinci-manual
api_key_file: /home/yimingz0/.openai_api_key
manual_prompt: configs/in-context/SBIC/manual-prompt.txt
test_samples: 500
test_seed: 44
data_config:
  data_dir: data/SBIC.v2
  subsample_common_stereotypes: True
generate_config:
  model: text-davinci-002
  temperature: 0.3