class: gpt-3
output_dir: outputs/in-context-manual/SBIC/davinci-sample
api_key_file: /home/yimingz0/.openai_api_key
manual_prompt: configs/in-context/SBIC/manual-prompt.txt
test_file: data/SBIC-special-sets/selected-0106.jsonl
generate_config:
  model: text-davinci-002
  temperature: 0.3