class: gpt-3
output_dir: outputs/in-context/implHate/curie-sample
api_key_file: /home/yimingz0/.openai_api_key
train_samples: 16
train_seed: 43
test_samples: 100
test_seed: 44
data_config:
  data_dir: data/implHate
  subsample_common_stereotypes: True
generate_config:
  model: text-curie-001
  temperature: 0.3