# base config (defines defaults for experiment config)
output_dir: outputs/debug
model_name: t5-small
data_config:
  data_dir: data/SBIC.v2-min
  batch_size: 4
  subsample_common_stereotypes: False
train_config:
  train_steps: 200
  grad_accumulation_steps: 4
  lr: 1e-4
  eval_every: 100
eval_config:
  monitor: stereotype-exact-match
  maximize: True
generate_config:
  do_sample: False