output_dir: outputs/in-context/debug
model: j1-grande
train_samples: 16
train_seed: 43
test_samples: 50
test_seed: 44
api_key_file: /home/yimingz0/.ai23_api_key
data_config:
  data_dir: data/SBIC.v2
  subsample_common_stereotypes: True
