output_dir: outputs/supervised/SBIC/t5-large
model_name: t5-large
data_config:
  subsample_common_stereotypes: True
  dev_size: 1000
  data_dir: data/SBIC.v2
  additional_test:
    - test-implHate
train_config:
  optimizer: adamw
  train_steps: 8000
  grad_accumulation_steps: 4
  lr: 2e-4
  eval_every: 800
