output_dir: outputs/supervised/implHate/t5-3b
model_name: t5-3b
data_config:
  subsample_common_stereotypes: True
  data_dir: data/implHate
train_config:
  optimizer: adafactor
  train_steps: 8000
  grad_accumulation_steps: 16
  lr: 2e-4
  eval_every: 800
