output_dir: outputs/supervised/implHate/t5-large
model_name: t5-large
data_config:
  subsample_common_stereotypes: True
  data_dir: data/implHate
train_config:
  optimizer: adamw
  train_steps: 8000
  grad_accumulation_steps: 4
  lr: 2e-4
  eval_every: 800
